[build]
dockerfile = "docker/Dockerfile"

[deploy]
name = "portfolio"
domains = ["portfolio.l3s.me", "l3s.me", "lucasbateson.com", "portfolio.lucasbateson.com"]
port = 3000

[env]
NODE_ENV = "production"
