services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - APP_NAME=${APP_NAME}
        - VERSION=${VERSION}
        - MAINTAINER_EMAIL=${MAINTAINER_EMAIL}
    image: ${IMAGE_FULL}
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      - "project=${APP_NAME}"
      - "environment=${ENVIRONMENT}"
      - "version=${IMAGE_TAG:-latest}"
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT}"
          memory: "${MEMORY_LIMIT}"
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:${APP_PORT}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    name: ${NETWORK_NAME}
    labels:
      - "project=${APP_NAME}"
      - "environment=${ENVIRONMENT}"
